$(document).ready(function(){
    $("#in").click(function(){
         $("img").width($("img").width()+100);
         $("img").height($("img").height()+100);
    });
    $("#out").click(function(){
         $("img").width($("img").width()-100);
         $("img").height($("img").height()-100);
    });
 });